repositoryID: "69ec076e-fe6f-4278-9ebe-1e9932effae3"
owners:
  - name: "mohgeis"
    email: "mohgeis@gmail.com"
keywords:
  - bookstack
  - wiki
  - documentation
links:
  - name: "Source"
    url: "https://github.com/mohgeis/bookstack-helm-chart"
  - name: "Project"
    url: "https://www.bookstackapp.com/"
