{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "bookstack.fullname" . }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  acme:
    # ACME server URL for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.certificate.email | default "admin@example.com" }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ include "bookstack.fullname" . }}-issuer-account-key
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.ingress.className | default "nginx" }}
{{- end }}
