{{- if and (not .Values.app.appKey.existingSecret) (or .Values.app.appKey.value .Values.app.appKey.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-appkey" (include "bookstack.fullname" .)) .Values.app.appKey.secretName }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.app.appKey.secretKey | default "app-key" }}: {{ if .Values.app.appKey.value }}{{ .Values.app.appKey.value | quote }}{{ else }}{{ printf "base64:%s" (printf "%s%s" (randAlphaNum 16) (randAlphaNum 16) | b64enc) | quote }}{{ end }}
{{- end }}
