name: Publish Helm Chart (OCI)

on:
  push:
    branches: [ main ]
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/workflows/publish-helm.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/workflows/publish-helm.yaml'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-helm
  cancel-in-progress: true

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Lint chart
        run: helm lint .

      - name: Render templates (dry-run validation)
        run: |
          helm template test-release . --values values.yaml >/dev/null

      - name: Package chart
        run: |
          mkdir -p repo
          helm package . --destination repo

      - name: Upload chart package (PR dry run)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: chart-packages
          path: repo/*.tgz

      - name: Login to GHCR (for OCI push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username "$GITHUB_ACTOR" --password-stdin

      - name: Push chart to GHCR (OCI)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          set -euo pipefail
          OWNER_LC=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          PKG=$(ls repo/*.tgz | head -n1)
          echo "Pushing $PKG to oci://ghcr.io/$OWNER_LC/bookstack"
          helm push "$PKG" oci://ghcr.io/$OWNER_LC/bookstack
